// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR API KEY',
    appId: 'YOUR API ID',
    messagingSenderId: 'YOUR ID',
    projectId: 'evervault-9d3e9',
    authDomain: 'evervault-9d3e9.firebaseapp.com',
    databaseURL: 'https://evervault-9d3e9-default-rtdb.firebaseio.com',
    storageBucket: 'evervault-9d3e9.firebasestorage.app',
    measurementId: 'G-SQNP0NXSZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVfpYTebSzz3fpaCuBV29WdmOXg4JwCvE',
    appId: '1:828698359246:android:128339684c23f60dd8279f',
    messagingSenderId: '828698359246',
    projectId: 'evervault-9d3e9',
    databaseURL: 'https://evervault-9d3e9-default-rtdb.firebaseio.com',
    storageBucket: 'evervault-9d3e9.firebasestorage.app',
  );
}
